version: '3'

services:
  node:
    build: ./node
    container_name: fc-node
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
      - /app/node_modules
    networks:
      - fc-network
    depends_on:
      mysql:
        condition: service_healthy
  
  nginx:
    image: "nginx:alpine"
    container_name: fc-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fc-network
    depends_on:
      - node
      - mysql

  mysql:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    container_name: fc-mysql
    ports:
      - "3306:3306"
    networks:
      - fc-network
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "fcdb"
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot -e 'SELECT 1 FROM information_schema.tables WHERE table_schema = \"fcdb\" LIMIT 1;'"]
      interval: 5s
      timeout: 20s
      retries: 10

networks:
  fc-network:
    driver: bridge